name: Build and Release

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build-darwin-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Binary on Linux and macOS
        shell: bash
        env:
          CGO_ENABLED: 1
        run: |
          go build \
            -o nomi-cli ./cmd/cli

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nomi-cli-darwin-arm64
          path: nomi-cli
